apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam
spec:
  selector:
    matchLabels:
      app: exam
  template:
    metadata:
      labels:
        app: exam
    spec:
      containers:
      - name: exam
        image: ankuradarsh/exam:0.1
